[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
extend-exclude = ["migrations", ".venv", "env", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "N"]

ignore = ["E402"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
