# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Vova Orig

from .base import (
    AccountNotFoundError,
    ApiProfileMissingError,
    AppError,
    BadChannelIdError,
    BadTgsError,
    ChannelNotFoundError,
    DomainError,
    DuplicateChannelError,
    GiftNotFoundError,
    GiftUnavailableError,
    InfrastructureError,
    InsufficientBalanceError,
    InvalidAccountIdError,
    InvalidBotTokenError,
    InvalidBuyTargetIdError,
    InvalidChatIdError,
    InvalidFallbackError,
    InvalidGiftIdError,
    InvalidNotifyChatIdError,
    InvalidTargetIdError,
    PeerIdInvalidError,
    TargetIdRequiredError,
    ValidationError,
)
from .http import handle_app_error, register_error_handler

__all__ = [
    "AppError",
    "DomainError",
    "InfrastructureError",
    "ValidationError",
    "ChannelNotFoundError",
    "DuplicateChannelError",
    "BadChannelIdError",
    "InvalidBotTokenError",
    "InvalidChatIdError",
    "InvalidTargetIdError",
    "PeerIdInvalidError",
    "InvalidFallbackError",
    "InvalidNotifyChatIdError",
    "InvalidBuyTargetIdError",
    "InvalidGiftIdError",
    "InvalidAccountIdError",
    "TargetIdRequiredError",
    "InvalidTargetIdError",
    "AccountNotFoundError",
    "ApiProfileMissingError",
    "GiftNotFoundError",
    "GiftUnavailableError",
    "InsufficientBalanceError",
    "BadTgsError",
    "handle_app_error",
    "register_error_handler",
]
