class ValidationErrorType:
    USERNAME_INVALID_CHARS = "username_invalid_chars"
    USERNAME_TOO_SHORT = "username_too_short"
    USERNAME_TOO_LONG = "username_too_long"
    PASSWORD_TOO_SHORT = "password_too_short"
    PASSWORD_TOO_LONG = "password_too_long"
    PASSWORD_WEAK = "password_weak"
    PASSWORD_NO_UPPERCASE = "password_no_uppercase"
    PASSWORD_NO_LOWERCASE = "password_no_lowercase"
    PASSWORD_NO_DIGIT = "password_no_digit"
    PASSWORD_NO_SPECIAL = "password_no_special"
    EMAIL_INVALID_FORMAT = "email_invalid_format"
    PHONE_INVALID_FORMAT = "phone_invalid_format"
    API_ID_INVALID = "api_id_invalid"
    API_HASH_INVALID = "api_hash_invalid"
    BOT_TOKEN_INVALID = "bot_token_invalid"
    CHAT_ID_INVALID = "chat_id_invalid"
    TARGET_ID_INVALID = "target_id_invalid"
    MISSING = "missing"
    STRING_TOO_SHORT = "string_too_short"
    STRING_TOO_LONG = "string_too_long"
    VALUE_ERROR = "value_error"
    TYPE_ERROR = "type_error"
    STRING_TYPE = "string_type"
    INT_PARSING = "int_parsing"
    BOOL_PARSING = "bool_parsing"
    EMAIL = "email"
    URL = "url"
    UUID = "uuid"
    DATETIME_PARSING = "datetime_parsing"
    JSON_INVALID = "json_invalid"
    REGEX = "regex"


__all__ = ["ValidationErrorType"]
